In [21]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Decision Tree.ipynb', 'groupStudy.csv']


In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
dataset = pd.read_csv('groupStudy.csv')

In [24]:
dataset

Position  Hours of study  Marks scored
0   Group-1               1            45
1   Group-2               2            50
2   Group-3               3            60
3   Group-4               4            80
4   Group-5               5           110
5   Group-6               6           150
6   Group-7               7           200
7   Group-8               8           300
8   Group-9               9           500
9  Group-10              10          1000

In [25]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
Position          10 non-null object
Hours of study    10 non-null int64
Marks scored      10 non-null int64
dtypes: int64(2), object(1)
memory usage: 320.0+ bytes


In [26]:
X = dataset.iloc[:,1:2].values
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [27]:
y = dataset.iloc[:,2].values
y

array([  45,   50,   60,   80,  110,  150,  200,  300,  500, 1000],
      dtype=int64)

In [28]:
#Fit data into Decision Tree 
from sklearn.tree import DecisionTreeRegressor

In [29]:
regressor = DecisionTreeRegressor()
regressor.fit(X,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [39]:
predictor = regressor.predict(5.5)

In [40]:
predictor

array([110.])