In [1]:
import os
print(os.listdir())

['.git', '.ipynb_checkpoints', 'Classification.ipynb', 'datatest.txt', 'datatest2.txt', 'datatraining.txt', 'Decision Tree.ipynb', 'groupStudy.csv', 'KNN.ipynb', 'LICENSE', 'Neural Network  MLPClassifier.ipynb', 'Social_Network_Ads.csv', 'SVM.ipynb']


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset.head(20)

User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   19            19000          0
1   15810944    Male   35            20000          0
2   15668575  Female   26            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   19            76000          0
5   15728773    Male   27            58000          0
6   15598044  Female   27            84000          0
7   15694829  Female   32           150000          1
8   15600575    Male   25            33000          0
9   15727311  Female   35            65000          0
10  15570769  Female   26            80000          0
11  15606274  Female   26            52000          0
12  15746139    Male   20            86000          0
13  15704987    Male   32            18000          0
14  15628972    Male   18            82000          0
15  15697686    Male   29            80000          0
16  15733883    Male   47            25000          1
17  15617482    Male   45            26000          1
18  15704583    Male   46            28000          1
19  15621083  Female   48            29000          1

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [5]:
X = dataset.iloc[:,2:4].values
y = dataset.iloc[:,4].values

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()

In [9]:
sc.fit_transform(X_train)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.6618781 ,  1.4122747 ],
       [-0.75841456, -1.53844728],
       [ 0.11041357,  0.21445687],
       [-0.95148747, -0.31141438],
       [ 0.30348649,  0.03916645],
       [ 1.461924  ,  0.36053221],
       [-1.33763331,  0.41896235],
       [-0.27573226,  0.53582263],
       [ 1.07577816,  0.12681166],
       [-1.04802393, -0.34062945],
       [ 1.84806984, -1.27551166],
       [-1.33763331, -1.48001714],
       [ 0.78616879,  1.38305963],
       [-1.72377914, -0.60356507],
       [-1.8203156 , -1.27551166],
       [-1.24109685, -1.39237193],
       [ 0.49655941,  1.85050073],
       [ 0.01387712, -0.25298424],
       [-1.24109685,  0.50660756],
       [-1.72377914,  0.47739249],
       [-0.1791958 ,  1.61678018],
       [-0.56534164,  1.90893087],
       [ 0.20695003,  2.11343636],
       [-0.27573226, -1.30472673],
       [-0.85495101,  0.38974728],
       [ 0.20695003, -0.36984452],
       [ 0.20695003, -0.36984452],
       [ 0.88270525,  1.0324788 ],
       [-1.72377914,

In [10]:
sc.fit(X_test)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
from sklearn.svm import SVC

In [12]:
classifier = SVC(kernel='linear')

In [13]:
classifier.fit(X_train,y_train.ravel())

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
from sklearn.metrics import classification_report,confusion_matrix

In [15]:
confusion_matrix(y_train,classifier.predict(X_train))

array([[180,  23],
       [ 36,  81]], dtype=int64)

In [16]:
confusion_matrix(y_test,classifier.predict(X_test))

array([[52,  2],
       [ 7, 19]], dtype=int64)

In [20]:
classification_report(y_test,classifier.predict(X_test))

'             precision    recall  f1-score   support\n\n          0       0.88      0.96      0.92        54\n          1       0.90      0.73      0.81        26\n\navg / total       0.89      0.89      0.88        80\n'